
const exerciseImages = [
    { name: 'Nessuna immagine', path: '' },
    { name: '1manusto90 (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-1MAN-BUSTO90-BG.png' },
    { name: 'Ab Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-AB-CRUNCH-BG.png' },
    { name: 'Addominali Obliqui Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/STRETCHING-ADDOMINALI-OBLIQUI-SU-FITBALL-BG.png' },
    { name: 'Addominali Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/STRETCHING-ADDOMINALI-SU-FITBALL-BG.png' },
    { name: 'Adductor Machine (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/CHIUSURE-ADDUCTOR-MACHINE-BG.png' },
    { name: 'Affondi Avanti Copro Libero (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-AVANTI-COPRO-LIBERO-BG.png' },
    { name: 'Affondi Avanti Prisoner (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-AVANTI-PRISONER-BG.png' },
    { name: 'Affondi Cable Machine (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-CABLE-MACHINE-BG.png' },
    { name: 'Affondi Frontali Manubri (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-FRONTALI-MANUBRI-BG.png' },
    { name: 'Affondi Frontaliilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-FRONTALI-BILANCIERE-BG.png' },
    { name: 'Affondi Laterali Su Step (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/AFFONDI LATERALI SU STEP.jpg' },
    { name: 'Affondi Lateraliilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-LATERALI-BILANCIERE-BG.png' },
    { name: 'Affondi Lateraliosu (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-LATERALI-BOSU-BG.png' },
    { name: 'Affondi Statici Manubri (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/quadricipiti-affondi-statici-manubri-bg.png' },
    { name: 'Affondi Statici Multipower (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-STATICI-MULTIPOWER-BG.png' },
    { name: 'Affondi Staticiilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-STATICI-BILANCIERE-BG.png' },
    { name: 'Affondiulgaro Cable Machine (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDI-BULGARO-CABLE-MACHINE-BG.png' },
    { name: 'Affondo Statico Globet Kettlebel (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/QUADRICIPITI-AFFONDO-STATICO-GLOBET-KETTLEBEL-BG.png' },
    { name: 'Affondo Statico Globet Kettlebel (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDO-STATICO-GLOBET-KETTLEBEL-BG.png' },
    { name: 'Affondoulgaro Manubri (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDO-BULGARO-MANUBRI-BG.png' },
    { name: 'Affondoulgaro Multipower (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-AFFONDO-BULGARO-MULTIPOWER-BG.png' },
    { name: 'Alzate Frontali Alternate Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-ALTERNATE-CABLE-MACHINE-BG.png' },
    { name: 'Alzate Frontali Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-CABLE-MACHINE-BG.png' },
    { name: 'Alzate Frontali Cavi (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-CAVI-BG.png' },
    { name: 'Alzate Frontali Manubri In Piedi (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-MANUBRI-IN-PIEDI-BG.png' },
    { name: 'Alzate Frontali Manubri Presa Inversa (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-MANUBRI-PRESA-INVERSA-BG.png' },
    { name: 'Alzate Frontali Manubri Seduto (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-MANUBRI-SEDUTO-BG.png' },
    { name: 'Alzate Frontali Panca Alta Ag (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-PANCA-ALTA-AG.png' },
    { name: 'Alzate Frontali Singolo Cavo (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-SINGOLO-CAVO-BG.png' },
    { name: 'Alzate Frontaliilanciere (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-FRONTALI-BILANCIERE-BG.png' },
    { name: 'Alzate Gamba Fianco A Terra (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-ALZATE-GAMBA-FIANCO-A-TERRA-BG.png' },
    { name: 'Alzate Gamba Stabilityall (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-ALZATE-GAMBA-STABILITY-BALL-BG.png' },
    { name: 'Alzate Gamba Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/ABDUTTORI-ALZATE-GAMBA-STABILITY-BALL-BG.png' },
    { name: 'Alzate Gambe Fianco Con Fitball (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/ABDUTTORI-ALZATE-GAMBE-FIANCO-CON-FITBALL-Bg.png' },
    { name: 'Alzate Gambe Fianco Con Fitball (FITBALL)', path: 'images/exercises/FITBALL/ABDUTTORI-ALZATE-GAMBE-FIANCO-CON-FITBALL-Bg.png' },
    { name: 'Alzate Gambe Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/GLUTEI-ALZATE-GAMBE-STABILITY-BALL-BG.png' },
    { name: 'Alzate Gambe Stabilityall (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-ALZATE-GAMBE-STABILITY-BALL-BG.png' },
    { name: 'Alzate Gambe Tese Con Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-ALZATE-GAMBE-TESE-CON-FITBALL-BG.png' },
    { name: 'Alzate Gambe Tese Con Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-ALZATE-GAMBE-TESE-CON-FITBALL-BG.png' },
    { name: 'Alzate Laterali Cavousto 90 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-CAVO-BUSTO-90-BG.png' },
    { name: 'Alzate Laterali Fitball (FITBALL)', path: 'images/exercises/FITBALL/SPALLE-ALZATE-LATERALI-FITBALL-BG.png' },
    { name: 'Alzate Laterali Fitball (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-FITBALL-BG.png' },
    { name: 'Alzate Laterali Kettlebell (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-KETTLEBELL-BG.png' },
    { name: 'Alzate Laterali Manubri Piedi (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-MANUBRI-PIEDI-BG.png' },
    { name: 'Alzate Laterali Manubri Seduto (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-MANUBRI-SEDUTO-BG.png' },
    { name: 'Alzate Laterali Manubrio Appoggio (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-MANUBRIO-APPOGGIO-BG.png' },
    { name: 'Alzate Laterali Manubrio Panca Alta (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-MANUBRIO-PANCA-ALTA-BG.png' },
    { name: 'Alzate Laterali Manubriusto 90 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-MANUBRI-BUSTO-90-BG.png' },
    { name: 'Alzate Laterali Singolo Cavo (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-SINGOLO-CAVO-BG.png' },
    { name: 'Alzate Lateraliusto Piegato Appoggio Panca (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ALZATE-LATERALI-BUSTO-PIEGATO-APPOGGIO-PANCA-BG.png' },
    { name: 'American Swing 1 Mano Kettlebell (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-AMERICAN-SWING-1-MANO-KETTLEBELL-BG.png' },
    { name: 'American Swing 1 Mano Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-AMERICAN-SWING-1-MANO-KETTLEBELL-BG.png' },
    { name: 'American Swing 2mani Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-AMERICAN-SWING-2MANI-KETTLEBELL-BG.png' },
    { name: 'And Jerk Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/SQUAT-AND-JERK-KETTLEBELL-BG.png' },
    { name: 'Aperture Manubri Panca Alta (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-APERTURE-MANUBRI-PANCA-ALTA-BG.png' },
    { name: 'Aperture Manubri Seduto Stabilityall 2 (FITBALL)', path: 'images/exercises/FITBALL/SPALLE-APERTURE-MANUBRI-SEDUTO-STABILITY-BALL-2-BG.png' },
    { name: 'Aperture Manubri Seduto Stabilityall 2 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-APERTURE-MANUBRI-SEDUTO-STABILITY-BALL-2-BG.png' },
    { name: 'Aperture Panca Alta Cavi (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-APERTURE-PANCA-ALTA-CAVI-BG.png' },
    { name: 'Aperture Panca Piana Manubri (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-APERTURE-PANCA-PIANA-MANUBRI-BG.png' },
    { name: 'Aperture Pancaassa Cavi (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-APERTURE-PANCA-BASSA-CAVI-BG.png' },
    { name: 'Aperture Pancaassa Manubri (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-APERTURE-PANCA-BASSA-MANUBRI-BG.png' },
    { name: 'Aperture Peck (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-APERTURE-PECK-BG.png' },
    { name: 'Arm Curl Machine (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-ARM-CURL-MACHINE-BG.png' },
    { name: 'Arm Curl Machine Alternato (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-ARM-CURL-MACHINE-ALTERNATO-BG.png' },
    { name: 'Arnold Press (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-ARNOLD-PRESS-BG.png' },
    { name: 'Back Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-BACK-MACHINE-BG.png' },
    { name: 'Balace Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/HIP-BALACE-FITBALL-BG.png' },
    { name: 'Balace Fitball (FITBALL)', path: 'images/exercises/FITBALL/HIP-BALACE-FITBALL-BG.png' },
    { name: 'Bike Seduto (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-BIKE-SEDUTO-B.png' },
    { name: 'Body Lancio Wallball Accosciata (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/TOTAL-BODY-LANCIO WALLBALL- ACCOSCIATA-BG.png' },
    { name: 'Body Lancio Wallball Accosciata (WALLBALL)', path: 'images/exercises/WALLBALL/TOTAL-BODY-LANCIO WALLBALL- ACCOSCIATA-BG.png' },
    { name: 'Body Squat And Press (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/TOTAL-BODY-SQUAT-AND-PRESS-BG.png' },
    { name: 'Body Squat And Press (WALLBALL)', path: 'images/exercises/WALLBALL/TOTAL-BODY-SQUAT-AND-PRESS-BG.png' },
    { name: 'Box Squat Copro Libero (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-BOX-SQUAT-COPRO-LIBERO-BG.png' },
    { name: 'Box Squatilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-BOX-SQUAT-BILANCIERE-BG.png' },
    { name: 'Bridge (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-BRIDGE-BG.png' },
    { name: 'Bridge Gambe Tese Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/GLUTEI-BRIDGE-GAMBE-TESE-SU-FITBALL-BG.png' },
    { name: 'Bridge Gambe Tese Su Fitball (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-BRIDGE-GAMBE-TESE-SU-FITBALL-BG.png' },
    { name: 'Bridge Piedi Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/GLUTEI-BRIDGE-PIEDI-SU-FITBALL-BG.png' },
    { name: 'Bridge Piedi Su Fitball (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-BRIDGE-PIEDI-SU-FITBALL-BG.png' },
    { name: 'Bridge Schiena Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/GLUTEI-BRIDGE-SCHIENA-SU-FITBALL-BG.png' },
    { name: 'Bridge Schiena Su Fitball (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-BRIDGE-SCHIENA-SU-FITBALL-BG.png' },
    { name: 'Bulgaro Fitball (FITBALL)', path: 'images/exercises/FITBALL/SUQAT-BULGARO-FITBALL-BG.png' },
    { name: 'Bulgaro Fitball (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/SUQAT-BULGARO-FITBALL-BG.png' },
    { name: 'Burpees (CARDIO)', path: 'images/exercises/CARDIO/FULLBODY-BURPEES-B.png' },
    { name: 'Calciata Dietro (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-CALCIATA-DIETRO-B.png' },
    { name: 'Calf Machine Piedi (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-MACHINE-PIEDI-BG.png' },
    { name: 'Calf Machine Seduto (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-MACHINE-SEDUTO-BG.png' },
    { name: 'Calf Multipower (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-MULTIPOWER-BG.png' },
    { name: 'Calf Piedi 2 Manubri (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-PIEDI-2-MANUBRI-BG.png' },
    { name: 'Calf Pressa 45 (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-PRESSA-45-BG.png' },
    { name: 'Calf Pressa Orizzontale (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-PRESSA-ORIZZONTALE-BG.png' },
    { name: 'Calf Singolo (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-SINGOLO-BG.png' },
    { name: 'Calf Singolo Cable Machine (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-SINGOLO-CABLE-MACHINE-BG.png' },
    { name: 'Calfilanciere In Piedi (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-BILANCIERE-IN-PIEDI-BG.png' },
    { name: 'Calfilanciere Seduto (POLPACCI)', path: 'images/exercises/POLPACCI/POLPACCI-CALF-BILANCIERE-SEDUTO-BG.png' },
    { name: 'Camminata Ginocchia Alte (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-CAMMINATA-GINOCCHIA-ALTE-B.png' },
    { name: 'Caperture Abductor Machine (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-CAPERTURE-ABDUCTOR-MACHINE-BG.png' },
    { name: 'Cavi Appoggio Panca (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-CAVI-APPOGGIO-PANCA-BG.png' },
    { name: 'Cavo Presa Inversa (TRICIPITI)', path: 'images/exercises/TRICIPITI/TITRATE-CAVO-PRESA-INVERSA-BG.png' },
    { name: 'Cerchi Manubri Panca Piana (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-CERCHI-MANUBRI-PANCA-PIANA-BG.png' },
    { name: 'Chest Fly Trx (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHEST-FLY-TRX-BG.png' },
    { name: 'Chest Fly Trx (TRX)', path: 'images/exercises/TRX/PETTORALI-CHEST-FLY-TRX-BG.png' },
    { name: 'Chest Press (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHEST-PRESS-BG.png' },
    { name: 'Chest Press Cable Machine (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHEST-PRESS-CABLE-MACHINE-BG.png' },
    { name: 'Chiusura Gambe Sdraiato Con Fitball (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/ADDUTTORI-CHIUSURA-GAMBE-SDRAIATO-CON-FITBALL-BG.png' },
    { name: 'Chiusura Gambe Sdraiato Con Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDUTTORI-CHIUSURA-GAMBE-SDRAIATO-CON-FITBALL-BG.png' },
    { name: 'Chiusure Addominal Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CHIUSURE-ADDOMINAL-MACHINE-BG.png' },
    { name: 'Chiusure Cable Machine (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-CABLE-MACHINE-BG.png' },
    { name: 'Chiusure Cavi Alti (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-CAVI-ALTI-BG.png' },
    { name: 'Chiusure Caviassi (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-CAVI-BASSI-BG.png' },
    { name: 'Chiusure Lat Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-CHIUSURE-LAT-MACHINE-BG.png' },
    { name: 'Chiusure Panca Piana Cavi (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-PANCA-PIANA-CAVI-BG.png' },
    { name: 'Chiusure Peck (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-PECK-BG.png' },
    { name: 'Chiusure Pectoral Machine (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-CHIUSURE-PECTORAL-MACHINE-BG.png' },
    { name: 'Chiusure Terra Gambe Piegate (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-chiusure-terra-gambe-piegate-BG.png' },
    { name: 'Chiusure Terra Gambe Tese (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-chiusure-terra-gambe-tese-BG.png' },
    { name: 'Clean One Arm Kettlebell V2 (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-CLEAN-ONE-ARM-KETTLEBELL-V2-BG.png' },
    { name: 'Clean One Arm Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-CLEAN-ONE-ARM-KETTLEBELL-V2-BG.png' },
    { name: 'Concentrato Manubrio Seduto (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CONCENTRATO-MANUBRIO-SEDUTO-BG.png' },
    { name: 'Corsa Tappeto (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-CORSA-TAPPETO-B.png' },
    { name: 'Criss Cross (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRISS-CROSS-BG.png' },
    { name: 'Criss Crossosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRISS-CROSS-BOSU-BG.png' },
    { name: 'Croci Inverse Alte Seduto Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/DORSALI-CROCI-INVERSE-ALTE-SEDUTO-CABLE-MACHINE-BG.png' },
    { name: 'Croci Inverse Cable In Piedi Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-CROCI-INVERSE-CABLE-IN-PIEDI-MACHINE-BG.png' },
    { name: 'Crossover Cavi Alti (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-CROSSOVER-CAVI-ALTI-BG.png' },
    { name: 'Crosstrainer Ellittica A (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-CROSSTRAINER-ELLITTICA-A.png' },
    { name: 'Crunch Cable Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOINALI-CRUNCH-CABLE-MACHINE-BG.png' },
    { name: 'Crunch Cavi (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-CAVI-BG.png' },
    { name: 'Crunch Con Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-CON-WALLBALL-BG.png' },
    { name: 'Crunch Con Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-CRUNCH-CON-WALLBALL-BG.png' },
    { name: 'Crunch Gambe 90 (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-GAMBE-90-BG.png' },
    { name: 'Crunch Gambe Su Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Crunch Gambe Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-CRUNCH-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Crunch Gambe Tese Alto (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-crunch-gambe-tese-alto-BG.png' },
    { name: 'Crunch Inversi Panca Reclinata (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-INVERSI-PANCA-RECLINATA-BG.png' },
    { name: 'Crunch Inverso Sdraiato Con Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-INVERSO-SDRAIATO-CON-FITBALL-BG.png' },
    { name: 'Crunch Inverso Sdraiato Con Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-CRUNCH-INVERSO-SDRAIATO-CON-FITBALL-BG.png' },
    { name: 'Crunch Inversoastoni (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-CRUNCH-INVERSO-BASTONI-BG.png' },
    { name: 'Crunch Kettlebell (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-KETTLEBELL-BG.png' },
    { name: 'Crunch Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/ADDOMINALI-CRUNCH-KETTLEBELL-BG.png' },
    { name: 'Crunch Libro Panca Piana (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-LIBRO-PANCA-PIANA-BG.png' },
    { name: 'Crunch Libroosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-LIBRO-BOSU-BG.png' },
    { name: 'Crunch Mani Avanti (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-MANI-AVANTI-BG.png' },
    { name: 'Crunch Obliqui A Terra (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-OBLIQUI-A-TERRA-BG.png' },
    { name: 'Crunch Obliqui Cable Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOINALI-CRUNCH-OBLIQUI-CABLE-MACHINE-BG.png' },
    { name: 'Crunch Obliqui Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-OBLIQUI-FITBALL-BG.png' },
    { name: 'Crunch Obliqui Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-CRUNCH-OBLIQUI-FITBALL-BG.png' },
    { name: 'Crunch Obliqui Gamba Piegata (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-OBLIQUI-GAMBA-PIEGATA-BG.png' },
    { name: 'Crunch Obliqui Panca (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-OBLIQUI-PANCA-BG.png' },
    { name: 'Crunch Obliquiosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-OBLIQUI-BOSU-BG.png' },
    { name: 'Crunch Panca Reclinata (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-PANCA-RECLINATA-BG.png' },
    { name: 'Crunch Panca Romana (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-CRUNCH-PANCA-ROMANA-BG.png' },
    { name: 'Crunch Parallele Piegate (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-PARALLELE-PIEGATE-BG.png' },
    { name: 'Crunch Parallele Tese (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-PARALLELE-TESE-BG.png' },
    { name: 'Crunch Sdraiato Con Panca (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-SDRAIATO-CON-PANCA-BG.png' },
    { name: 'Crunch Stabilityall (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-STABILITY-BALL-BG.png' },
    { name: 'Crunch Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-CRUNCH-STABILITY-BALL-BG.png' },
    { name: 'Crunch Terra (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-CRUNCH-TERRA-BG.png' },
    { name: 'Crunch Terra Alternato (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-CRUNCH-TERRA-ALTERNATO-BG.png' },
    { name: 'Crunch Tocco Caviglie (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-CRUNCH-TOCCO-CAVIGLIE-BG.png' },
    { name: 'Crunch Trx (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-TRX-BG.png' },
    { name: 'Crunch Trx (TRX)', path: 'images/exercises/TRX/ADDOMINALI-CRUNCH-TRX-BG.png' },
    { name: 'Crunchosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-CRUNCH-BOSU-BG.png' },
    { name: 'Curl Cavi Alti (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-CAVI-ALTI-BG.png' },
    { name: 'Curl Cavi Corda (BICIPITI)', path: 'images/exercises/BICIPITI/HAMMER-CURL-CAVI-CORDA-BG.png' },
    { name: 'Curl Cavoasso (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-CAVO-BASSO-BG.png' },
    { name: 'Curl Cavoasso Singolo (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-CAVO-BASSO-SINGOLO-BG.png' },
    { name: 'Curl Concentrato Stabilityall (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITU-CURL-CONCENTRATO-STABILITY-BALL-BG.png' },
    { name: 'Curl Concentrato Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/BICIPITU-CURL-CONCENTRATO-STABILITY-BALL-BG.png' },
    { name: 'Curl Hammer Alternato (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-HAMMER-ALTERNATO-BG.png' },
    { name: 'Curl Hammer Alternato (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/BICIPITI-CURL-HAMMER-ALTERNATO-BG.png' },
    { name: 'Curl Hammer Kettlebell (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-HAMMER-KETTLEBELL-BG.png' },
    { name: 'Curl Hammer Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/BICIPITI-CURL-HAMMER-KETTLEBELL-BG.png' },
    { name: 'Curl Inverso Polso Manubrio Su Panca (AVAMBRACCI)', path: 'images/exercises/AVAMBRACCI/AVAMBRACCI-CURL-INVERSO-POLSO-MANUBRIO-SU-PANCA-BG.png' },
    { name: 'Curl Inversoilanciere (AVAMBRACCI)', path: 'images/exercises/AVAMBRACCI/AVAMBRACCI-CURL-INVERSO-BILANCIERE-BG.png' },
    { name: 'Curl Manubri Alternato Piedi (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRI-ALTERNATO-PIEDI-BG.png' },
    { name: 'Curl Manubri Martello Alternato (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRI-MARTELLO-ALTERNATO-BG.png' },
    { name: 'Curl Manubri Piedi (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRI-PIEDI-BG.png' },
    { name: 'Curl Manubri Seduto (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRI-SEDUTO-BG.png' },
    { name: 'Curl Manubri Seduto Mani Fuori (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITU-CURL-MANUBRI-SEDUTO-MANI-FUORI-BG.png' },
    { name: 'Curl Manubri Seduto Panca Alta (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRI-SEDUTO-PANCA-ALTA-BG.png' },
    { name: 'Curl Manubrio Concentrato Panca Alta (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-MANUBRIO-CONCENTRATO-PANCA-ALTA-BG.png' },
    { name: 'Curl Panca Scott 1 Manubrio (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-PANCA-SCOTT-1-MANUBRIO-BG.png' },
    { name: 'Curl Panca Scottilanciere (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-PANCA-SCOTT-BILANCIERE-BG.png' },
    { name: 'Curl Polso Manubrio Su Panca (AVAMBRACCI)', path: 'images/exercises/AVAMBRACCI/AVAMBRACCI-CURL-POLSO-MANUBRIO-SU-PANCA-BG.png' },
    { name: 'Curl Trx (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-TRX-BG.png' },
    { name: 'Curl Trx (TRX)', path: 'images/exercises/TRX/BICIPITI-CURL-TRX-BG.png' },
    { name: 'Curliceps Machine (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-BICEPS-MACHINE-BG.png' },
    { name: 'Curlilanciere Ez (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-BILANCIERE-EZ-BG.png' },
    { name: 'Curlilanciere Ez Largo (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-BILANCIERE-EZ-LARGO-BG.png' },
    { name: 'Curlilanciere Hammer Piedi (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-BILANCIERE-HAMMER-PIEDI-BG.png' },
    { name: 'Curlilanciere Su Panca (AVAMBRACCI)', path: 'images/exercises/AVAMBRACCI/AVAMBRACCI-CURL-BILANCIERE-SU-PANCA-BG.png' },
    { name: 'Curlilancieri Piedi (BICIPITI)', path: 'images/exercises/BICIPITI/BICIPITI-CURL-BILANCIERI-PIEDI-BG.png' },
    { name: 'Cyclette (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-CYCLETTE-B.png' },
    { name: 'Dips Gomiti Stretti (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-DIPS-GOMITI-STRETTI-BG.png' },
    { name: 'Dips Panche (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-DIPS-PANCHE-BG.png' },
    { name: 'Dips Parallele (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DIPS-PARALLELE-BG.png' },
    { name: 'Distensione Terra Appoggio (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONE-TERRA-APPOGGIO-BG.png' },
    { name: 'Distensioni Accosciata Wallball (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-DISTENSIONI-ACCOSCIATA-WALLBALL-BG.png' },
    { name: 'Distensioni Accosciata Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/SPALLE-DISTENSIONI-ACCOSCIATA-WALLBALL-BG.png' },
    { name: 'Distensioni Con Gambe Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/PETTORALI-DISTENSIONI-CON-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Distensioni Con Gambe Su Fitball (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-CON-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Distensioni In Piedi Alt Cable Machine (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-IN-PIEDI-ALT-CABLE-MACHINE-BG.png' },
    { name: 'Distensioni In Piedi Cable Machine (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-IN-PIEDI-CABLE-MACHINE-BG.png' },
    { name: 'Distensioni Seduto Wallball (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-DISTENSIONI- SEDUTO-WALLBALL-BG.png' },
    { name: 'Distensioni Seduto Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/SPALLE-DISTENSIONI- SEDUTO-WALLBALL-BG.png' },
    { name: 'Distensioni Sopra La Testa Con Wallball (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-DISTENSIONI-SOPRA-LA-TESTA-CON-WALLBALL-BG.png' },
    { name: 'Distensioni Sopra La Testa Con Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/SPALLE-DISTENSIONI-SOPRA-LA-TESTA-CON-WALLBALL-BG.png' },
    { name: 'Distensioni Strette Multipower (TRICIPITI)', path: 'images/exercises/TRICIPITI/Tricipiti-distensioni-strette-multipower-BG.png' },
    { name: 'Distensioni Subosu (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-SUBOSU-BG.png' },
    { name: 'Distensioni Terra (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-TERRA-BG.png' },
    { name: 'Distensioni Terra Trx (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-DISTENSIONI-TERRA-TRX-BG.png' },
    { name: 'Distensioni Terra Trx (TRX)', path: 'images/exercises/TRX/PETTORALI-DISTENSIONI-TERRA-TRX-BG.png' },
    { name: 'Distensioniilanciere Panca Alta Multipower (PETTORALI)', path: 'images/exercises/PETTORALI/pettorali-distensioni-bilanciere-panca-alta-multipower-BG.png' },
    { name: 'Distensioniilanciere Panca Piana Multipower (PETTORALI)', path: 'images/exercises/PETTORALI/pettorali-distensioni-bilanciere-panca-piana-multipower-BG.png' },
    { name: 'Distensioniilanciere Pancaassa Multipower (PETTORALI)', path: 'images/exercises/PETTORALI/pettorali-distensioni-bilanciere-panca-bassa-multipower-BG.png' },
    { name: 'Doppio Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-DOPPIO-CRUNCH-BG.png' },
    { name: 'Elastico Acceleratore (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-ELASTICO ACCELERATORE.jpg' },
    { name: 'Estensioni Manubri Seduto (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-ESTENSIONI-MANUBRI-SEDUTO-BG.png' },
    { name: 'Excite Top (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-EXCITE-TOP-B.png' },
    { name: 'Extrarotazioni Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-EXTRAROTAZIONI-CABLE-MACHINE-BG.png' },
    { name: 'Floor Press 2 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/PETTORALI-FLOOR-PRESS-2-KETTLEBELL-BG.png' },
    { name: 'Floor Press 2 Kettlebell (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-FLOOR-PRESS-2-KETTLEBELL-BG.png' },
    { name: 'Floor Press One Arm (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/PETTORALI-FLOOR-PRESS-ONE-ARM-BG.png' },
    { name: 'Floor Press One Arm (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-FLOOR-PRESS-ONE-ARM-BG.png' },
    { name: 'French Pres 1man Seduto (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRES-1MAN-SEDUTO-BG.png' },
    { name: 'French Press 1man Panca (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRESS-1MAN-PANCA-BG.png' },
    { name: 'French Press 2man Panca (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRESS-2MAN-PANCA-BG.png' },
    { name: 'French Press Manubri Fitballbg (FITBALL)', path: 'images/exercises/FITBALL/TRICIPITI-FRENCH-PRESS-MANUBRI-FITBALLBG.png' },
    { name: 'French Press Manubri Fitballbg (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRESS-MANUBRI-FITBALLBG.png' },
    { name: 'French Press Sedutoilanciere Ez (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRESS-SEDUTO-BILANCIERE-EZ-BG.png' },
    { name: 'French Pressilanciere Panca (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-FRENCH-PRESS-BILANCIERE-PANCA-BG.png' },
    { name: 'Front Squat Clean Parallelo (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-FRONT-SQUAT-CLEAN-PARALLELO-BG.png' },
    { name: 'Front Squat Cleanilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-FRONT-SQUAT-CLEAN-BILANCIERE-BG.png' },
    { name: 'Front Squat Cross (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-FRONT-SQUAT-CROSS-BG.png' },
    { name: 'Front Squat Presa Clean Multipower (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/quadricipiti-front-squat-presa-clean-multipower-BG.png' },
    { name: 'Front Squat Presa Cross Multipower (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/quadricipiti-front-squat-presa-cross-multipower-BG.png' },
    { name: 'Front Squat Wallball (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-FRONT-SQUAT-WALLBALL-BG.png' },
    { name: 'Front Squat Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/QUADRICIPITI-FRONT-SQUAT-WALLBALL-BG.png' },
    { name: 'Front Squatilanciere Parallelo (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-FRONT-SQUAT-BILANCIERE-PARALLELO-BG.png' },
    { name: 'Goblet Squat Fitball V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/QUADRICIPITI-GOBLET-SQUAT-FITBALL-V2-BG.png' },
    { name: 'Goblet Squat Fitball V2 (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-GOBLET-SQUAT-FITBALL-V2-BG.png' },
    { name: 'Goblet Squat Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/QUADRICIPITI-GOBLET-SQUAT-KETTLEBELL-V2-BG.png' },
    { name: 'Goblet Squat Kettlebell V2 (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-GOBLET-SQUAT-KETTLEBELL-V2-BG.png' },
    { name: 'Goblet Squat Wallball (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-GOBLET-SQUAT-WALLBALL-BG.png' },
    { name: 'Goblet Squat Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/QUADRICIPITI-GOBLET-SQUAT-WALLBALL-BG.png' },
    { name: 'Good Moning (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-GOOD-MONING-BG.png' },
    { name: 'Hack Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-HACK-SQUAT-BG.png' },
    { name: 'High Pull 1 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/SPALLE-HIGH-PULL-1-KETTLEBELL-BG.png' },
    { name: 'Hyperextension (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/CRUNCH-HYPEREXTENSION-BG.png' },
    { name: 'Hyperextension Stabilityall V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-HYPEREXTENSION-STABILITY-BALL-V2-BG.png' },
    { name: 'Hyperextension Stabilityall V2 (FITBALL)', path: 'images/exercises/FITBALL/DORSALI-HYPEREXTENSION-STABILITY-BALL-V2-BG.png' },
    { name: 'Hypextension V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-HYPEXTENSION-V2-BG.png' },
    { name: 'Incrocio Gambe Alternato Sdraiato (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-INCROCIO-GAMBE-ALTERNATO-SDRAIATO-BG.png' },
    { name: 'Intrarotazioni Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-INTRAROTAZIONI-CABLE-MACHINE-BG.png' },
    { name: 'Jackknife Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-JACKKNIFE-FITBALL-BG.png' },
    { name: 'Jackknife Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-JACKKNIFE-FITBALL-BG.png' },
    { name: 'Jump Mani Terra (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-jump-mani-terra-BG.png' },
    { name: 'Jumping Jack (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-jumping-jack-B.png' },
    { name: 'Lancio Wallball In Alto (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LANCIO-WALLBALL-IN-ALTO-BG.png' },
    { name: 'Lancio Wallball In Alto (WALLBALL)', path: 'images/exercises/WALLBALL/SPALLE-LANCIO-WALLBALL-IN-ALTO-BG.png' },
    { name: 'Lancio Wallball In Avanti (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-LANCIO-WALLBALL-IN-AVANTI-BG.png' },
    { name: 'Lancio Wallball In Avanti (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-LANCIO-WALLBALL-IN-AVANTI-BG.png' },
    { name: 'Lat Machine Avanti V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-LAT-MACHINE-AVANTI-V2-BG.png' },
    { name: 'Lat Machine Dietro V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-LAT-MACHINE-DIETRO-V2-BG.png' },
    { name: 'Lat Machine Inverso (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-LAT-MACHINE-INVERSO-BG.png' },
    { name: 'Lateral Deltoid Machine (SPALLE)', path: 'images/exercises/SPALLE/APERTURE-LATERAL-DELTOID-MACHINE-BG.png' },
    { name: 'Laterali Cavi (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/PIEGAMENTI-LATERALI-CAVI-BG.png' },
    { name: 'Laterali Sedutousto 90 (SPALLE)', path: 'images/exercises/SPALLE/ALZATE-LATERALI-SEDUTO-BUSTO-90-BG.png' },
    { name: 'Leg Culr Standing 2 (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-LEG-CULR-STANDING-2-BG.png' },
    { name: 'Leg Curl Sdraiato (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-LEG-CURL-SDRAIATO-BG.png' },
    { name: 'Leg Curl Seduto (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-LEG-CURL-SEDUTO-BG.png' },
    { name: 'Leg Curl Su Fitball (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-LEG-CURL-SU-FITBALL-BG.png' },
    { name: 'Leg Curl Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/FEMORALI-LEG-CURL-SU-FITBALL-BG.png' },
    { name: 'Leg Extension (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-LEG-EXTENSION-BG.png' },
    { name: 'Leg Extension Mono (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-LEG-EXTENSION-MONO-BG.png' },
    { name: 'Leg Knee Raise (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-LEG-KNEE-RAISE-BG.png' },
    { name: 'Leg Press Orizzontale Mono (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-LEG-PRESS-ORIZZONTALE-MONO-BG.png' },
    { name: 'Leg Raise (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-LEG-RAISE-BG.png' },
    { name: 'Leg Raise Alternato (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-LEG-RAISE-ALTERNATO-BG.png' },
    { name: 'Lento Avantiilanciere In Piedi (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-AVANTI-BILANCIERE-IN-PIEDI-BG.png' },
    { name: 'Lento Avantiilanciere Seduto (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-AVANTI-BILANCIERE-SEDUTO-BG.png' },
    { name: 'Lento Dietro Multipower (SPALLE)', path: 'images/exercises/SPALLE/spalle-lento-dietro-multipower-BG.png' },
    { name: 'Lento Dietroilanciere 2 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-DIETRO-BILANCIERE-2-BG.png' },
    { name: 'Lento Manubri Alternato (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-MANUBRI-ALTERNATO-BG.png' },
    { name: 'Lento Manubri Fitall (FITBALL)', path: 'images/exercises/FITBALL/SPALLE-LENTO-MANUBRI-FIT-BALL-BG.png' },
    { name: 'Lento Manubri Fitall (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-MANUBRI-FIT-BALL-BG.png' },
    { name: 'Lento Manubri In Pidi (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-LENTO-MANUBRI-IN-PIDI-BG.png' },
    { name: 'Lombari A Terra (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-LOMBARI-A-TERRA-BG.png' },
    { name: 'Low Row V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-LOW-ROW-V2-BG.png' },
    { name: 'Manubri Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/APERTURE-MANUBRI-STABILITY-BALL-BG.png' },
    { name: 'Manubri Stabilityall (PETTORALI)', path: 'images/exercises/PETTORALI/APERTURE-MANUBRI-STABILITY-BALL-BG.png' },
    { name: 'Mento Manubri (TRAPEZI)', path: 'images/exercises/TRAPEZI/TIRATE-MENTO-MANUBRI-BG.png' },
    { name: 'Military Press Multipower (SPALLE)', path: 'images/exercises/SPALLE/spalle-military-press-multipower-BG.png' },
    { name: 'Mountain Climber Doppio (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-MOUNTAIN-CLIMBER-DOPPIO-BG.png' },
    { name: 'Obliqui Crunch Gambe Su Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-OBLIQUI-CRUNCH-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Obliqui Crunch Gambe Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-OBLIQUI-CRUNCH-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Over Head Squat Fitball (FITBALL)', path: 'images/exercises/FITBALL/QUADRICIPTI-OVER-HEAD-SQUAT-FITBALL-BG.png' },
    { name: 'Overhead Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-OVERHEAD-SQUAT-BG.png' },
    { name: 'Overhead Squat (WALLBALL)', path: 'images/exercises/WALLBALL/QUADRICIPITI-OVERHEAD-SQUAT-BG.png' },
    { name: 'Piegamenti Laterali Manubri (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-PIEGAMENTI-LATERALI-MANUBRI-BG.png' },
    { name: 'Piegamenti Lateraliastoni (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-PIEGAMENTI-LATERALI-BASTONI-BG.png' },
    { name: 'Pinnate Gambe Alternate (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDIMINALI-PINNATE-GAMBE-ALTERNATE-BG.png' },
    { name: 'Pistol Squat Trx (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-PISTOL-SQUAT-TRX-BG.png' },
    { name: 'Pistol Squat Trx (TRX)', path: 'images/exercises/TRX/QUADRICIPITI-PISTOL-SQUAT-TRX-BG.png' },
    { name: 'Plank 2 (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-2-BG.png' },
    { name: 'Plank Elevazione Gambe Alternato (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-plank-elevazione-gambe-alternato-BG.png' },
    { name: 'Plank Gambe Su Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Plank Gambe Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-PLANK-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Plank In Torsione (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/PLANK IN TORSIONE.jpg' },
    { name: 'Plank Su Mani E Gomiti (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/PLANK SU MANI E GOMITI.jpg' },
    { name: 'Plank Superman (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-plank-superman-BG.png' },
    { name: 'Plank Trx (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-TRX-BG.png' },
    { name: 'Plank Trx (TRX)', path: 'images/exercises/TRX/ADDOMINALI-PLANK-TRX-BG.png' },
    { name: 'Plankosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-bosu-BG.png' },
    { name: 'Plankracci Su Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-BRACCI-SU-FITBALL-BG.png' },
    { name: 'Plankracci Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-PLANK-BRACCI-SU-FITBALL-BG.png' },
    { name: 'Plankraccia Tese (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-PLANK-BRACCIA-TESE-BG.png' },
    { name: 'Ponte 1 Gambaosu (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-PONTE-1-GAMBA-BOSU-BG.png' },
    { name: 'Press 1man Seduto (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-PRESS-1MAN-SEDUTO-BG.png' },
    { name: 'Press Manubri (SPALLE)', path: 'images/exercises/SPALLE/PUSH-PRESS-MANUBRI-BG.png' },
    { name: 'Press Orizontale (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/LEG-PRESS-ORIZONTALE-BG.png' },
    { name: 'Press Piedi 2 Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/SPALLE-PRESS-PIEDI-2-KETTLEBELL-V2-BG.png' },
    { name: 'Press Piedi 2 Kettlebell V2 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-PRESS-PIEDI-2-KETTLEBELL-V2-BG.png' },
    { name: 'Press Piedi Singolo Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/SPALLE-PRESS-PIEDI-SINGOLO-KETTLEBELL-V2-BG.png' },
    { name: 'Press Piedi Singolo Kettlebell V2 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-PRESS-PIEDI-SINGOLO-KETTLEBELL-V2-BG.png' },
    { name: 'Pressa 45 (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-PRESSA-45-BG.png' },
    { name: 'Pull Down V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULL-DOWN-V2-BG.png' },
    { name: 'Pulley Alto Cable Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-ALTO-CABLE-MACHINE-BG.png' },
    { name: 'Pulley Alto Inverso (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-ALTO-INVERSO-BG.png' },
    { name: 'Pulley Alto Trazyar (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-ALTO-TRAZY-BAR-BG.png' },
    { name: 'Pulley Alto Triangolo (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-ALTO-TRIANGOLO-BG.png' },
    { name: 'Pulley Cable Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-CABLE-MACHINE-BG.png' },
    { name: 'Pulley In Piedi Cable Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-IN-PIEDI-CABLE-MACHINE-BG.png' },
    { name: 'Pulley Inverso (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-INVERSO-BG.png' },
    { name: 'Pulley Trazyar (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-TRAZY-BAR-BG.png' },
    { name: 'Pulley Triangolo (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-PULLEY-TRIANGOLO-BG.png' },
    { name: 'Pullover Manubrio (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-PULLOVER-MANUBRIO-BG.png' },
    { name: 'Pulloverilanciere (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-PULLOVER-BILANCIERE-BG.png' },
    { name: 'Pulse Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-PULSE-SQUAT-BG.png' },
    { name: 'Push Cavi 2mani (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-PUSH-CAVI-2MANI-BG.png' },
    { name: 'Push Press 1 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/SPALLE-PUSH-PRESS-1-KETTLEBELL-BG.png' },
    { name: 'Push Press 1 Kettlebell (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-PUSH-PRESS-1-KETTLEBELL-BG.png' },
    { name: 'Push Up Stretti Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/TRICIPITI-PUSH-UP-STRETTI-KETTLEBELL-BG.png' },
    { name: 'Push Up Stretti Kettlebell (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-PUSH-UP-STRETTI-KETTLEBELL-BG.png' },
    { name: 'Quadriciiti American Swing And Squat Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-QUADRICIITI-AMERICAN-SWING-AND-SQUAT-KETTLEBELL-BG.png' },
    { name: 'Quadricipiti Amrican Squat Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-QUADRICIPITI-AMRICAN-SQUAT-KETTLEBELL-BG.png' },
    { name: 'Quadricipiti Amrican Squat Kettlebell (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/GLUTEI-QUADRICIPITI-AMRICAN-SQUAT-KETTLEBELL-BG.png' },
    { name: 'Rematore 2 Kettlebell V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-2-KETTLEBELL-V2-BG.png' },
    { name: 'Rematore 2 Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/DORSALI-REMATORE-2-KETTLEBELL-V2-BG.png' },
    { name: 'Rematore 2 Manubri V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-2-MANUBRI-V2-BG.png' },
    { name: 'Rematore Manubrio Su Panca (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-MANUBRIO-SU-PANCA-BG.png' },
    { name: 'Rematore Manubrioosu (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-MANUBRIO-BOSU-BG.png' },
    { name: 'Rematore Multipower (DORSALI)', path: 'images/exercises/DORSALI/dorsali-rematore-multipower-BG.png' },
    { name: 'Rematore Su Fitball V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-SU-FITBALL-v2-BG.png' },
    { name: 'Rematore Su Fitball V2 (FITBALL)', path: 'images/exercises/FITBALL/DORSALI-REMATORE-SU-FITBALL-v2-BG.png' },
    { name: 'Rematoreilanciere Appoggio Testa V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-BILANCIERE-APPOGGIO-TESTA-V2-BG.png' },
    { name: 'Rematoreilanciere V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-REMATORE-BILANCIERE-V2-BG.png' },
    { name: 'Renegade Kettlebell (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-RENEGADE-KETTLEBELL-BG.png' },
    { name: 'Renegade Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/DORSALI-RENEGADE-KETTLEBELL-BG.png' },
    { name: 'Reverse Fly Trx (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-REVERSE-FLY-TRX-BG.png' },
    { name: 'Reverse Fly Trx (TRX)', path: 'images/exercises/TRX/SPALLE-REVERSE-FLY-TRX-BG.png' },
    { name: 'Rotazione Manubrio Su Panca (AVAMBRACCI)', path: 'images/exercises/AVAMBRACCI/AVAMBRACCI-ROTAZIONE-MANUBRIO-SU-PANCA-BG.png' },
    { name: 'Rotazioniacino Gambe Su Fitball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-ROTAZIONI-BACINO-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Rotazioniacino Gambe Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/ADDOMINALI-ROTAZIONI-BACINO-GAMBE-SU-FITBALL-BG.png' },
    { name: 'Row Trx (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-ROW-TRX-BG.png' },
    { name: 'Row Trx (TRX)', path: 'images/exercises/TRX/DORSALI-ROW-TRX-BG.png' },
    { name: 'Russian Situp A Terra (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-SITUP-A-TERRA-BG.png' },
    { name: 'Russian Situp Con Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADOMINALI-RUSSIAN-SITUP-CON-WALLBALL-BG.png' },
    { name: 'Russian Situp Extended (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-SITUP-EXTENDED-BG.png' },
    { name: 'Russian Situp Extended (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-RUSSIAN-SITUP-EXTENDED-BG.png' },
    { name: 'Russian Situp One Arm Kettlebell (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-SITUP-ONE-ARM-KETTLEBELL-BG.png' },
    { name: 'Russian Situp One Arm Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/ADDOMINALI-RUSSIAN-SITUP-ONE-ARM-KETTLEBELL-BG.png' },
    { name: 'Russian Twist (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-TWIST-BG.png' },
    { name: 'Russian Twist Kettlebell (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-TWIST-KETTLEBELL-BG.png' },
    { name: 'Russian Twist Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/ADDOMINALI-RUSSIAN-TWIST-KETTLEBELL-BG.png' },
    { name: 'Russian Twistosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-RUSSIAN-TWIST-BOSU-BG.png' },
    { name: 'Sacco (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-SACCO.jpg' },
    { name: 'Shoulder Press (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-SHOULDER-PRESS-BG.png' },
    { name: 'Shrug Manubri Piedi (TRAPEZI)', path: 'images/exercises/TRAPEZI/TRAPEZI-SHRUG-MANUBRI-PIEDI-BG.png' },
    { name: 'Shrug Multipower (TRAPEZI)', path: 'images/exercises/TRAPEZI/trapezi-shrug-multipower-BG.png' },
    { name: 'Shrugilanciere Dietro Piedi (TRAPEZI)', path: 'images/exercises/TRAPEZI/TRAPEZI-SHRUG-BILANCIERE-DIETRO-PIEDI-BG.png' },
    { name: 'Shrugs Caviassi (TRAPEZI)', path: 'images/exercises/TRAPEZI/TRAPEZI-SHRUGS-CAVI-BASSI-BG.png' },
    { name: 'Side Crunch Trx (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SIDE-CRUNCH-TRX-Bg.png' },
    { name: 'Side Crunch Trx (TRX)', path: 'images/exercises/TRX/ADDOMINALI-SIDE-CRUNCH-TRX-Bg.png' },
    { name: 'Side Plank (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SIDE-PLANK-BG.png' },
    { name: 'Side Plank Facilitato (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SIDE-PLANK-FACILITATO-BG.png' },
    { name: 'Side Plank Star (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-side-plank-star-BG.png' },
    { name: 'Side Plankosu (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SIDE-PLANK-BOSU-BG.png' },
    { name: 'Side Plankraccio Teso (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-side-plank-braccio-teso-BG.png' },
    { name: 'Situp A Terra (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SITUP-A-TERRA-BG.png' },
    { name: 'Situp Lancio Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SITUP-LANCIO- WALLBALL-BG.png' },
    { name: 'Situp Lancio Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-SITUP-LANCIO- WALLBALL-BG.png' },
    { name: 'Skip Alto (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-SKIP-ALTO-B.png' },
    { name: 'Skipasso (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-SKIP-BASSO-B.png' },
    { name: 'Slaci Post Gamba Piegataosu (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLACI-POST-GAMBA-PIEGATA-BOSU-BG.png' },
    { name: 'Slamball Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SLAMBALL-WALLBALL-BG.png' },
    { name: 'Slanci Esterni Multi Hip (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-SLANCI-ESTERNI-MULTI-HIP-BG.png' },
    { name: 'Slanci Gamba Cavi (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/ADDUTTORI-SLANCI-GAMBA-CAVI-BG.png' },
    { name: 'Slanci Gamba Esterni Cavi (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-SLANCI-GAMBA-ESTERNI-CAVI-BG.png' },
    { name: 'Slanci Gamba Piegata Quadrupedia (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORE-SLANCI-GAMBA-PIEGATA-QUADRUPEDIA-BG.png' },
    { name: 'Slanci Gamba Posteriori In Piedi (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLANCI-GAMBA-POSTERIORI-IN-PIEDI-BG.png' },
    { name: 'Slanci Gamba Tesaosu (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLANCI-GAMBA-TESA-BOSU-BG.png' },
    { name: 'Slanci Gambaosu (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORE-SLANCI-GAMBA-BOSU-BG.png' },
    { name: 'Slanci Interni Multi Hip (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/ADDUTTORI-SLANCI-INTERNI-MULTI-HIP-BG.png' },
    { name: 'Slanci Laterali Gamba In Piedi (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-SLANCI-LATERALI-GAMBA-IN-PIEDI-BG.png' },
    { name: 'Slanci Post Gamba Piegata (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLANCI-POST-GAMBA-PIEGATA-BG.png' },
    { name: 'Slanci Post Gamba Tesa (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLANCI-POST-GAMBA-TESA-BG.png' },
    { name: 'Slanci Posteriori Multi Hip (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SLANCI-POSTERIORI-MULTI-HIP-BG.png' },
    { name: 'Snatch One Arm Kt V2 (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SNATCH-ONE-ARM-KT-V2-BG.png' },
    { name: 'Snatch One Arm Kt V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SNATCH-ONE-ARM-KT-V2-BG.png' },
    { name: 'Sollevamento Gambe 90 Sbarra (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-SOLLEVAMENTO-GAMBE-90-SBARRA-BG.png' },
    { name: 'Spalle Clean And Jerk 1 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SPALLE-CLEAN-AND-JERK-1-KETTLEBELL-BG.png' },
    { name: 'Spalle Clean And Press 1 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SPALLE-CLEAN-AND-PRESS-1-KETTLEBELL-BG.png' },
    { name: 'Spinte Alternate Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-SPINTE-ALTERNATE-CABLE-MACHINE-BG.png' },
    { name: 'Spinte Alto Gambe Tese (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-Spinte-Alto-gambe-tese-BG.png' },
    { name: 'Spinte Alto Manubrio (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMNALI-SPINTE-ALTO-MANUBRIO-BG.png' },
    { name: 'Spinte Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-SPINTE-CABLE-MACHINE-BG.png' },
    { name: 'Spinte Frontali Multi Hip (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SPINTE-FRONTALI-MULTI-HIP-BG.png' },
    { name: 'Spinte Gamba Sdraiato (ADDUTTORI)', path: 'images/exercises/ADDUTTORI/ADDUTTORI-SPINTE-GAMBA-SDRAIATO-BG.png' },
    { name: 'Spinte Gluteus Machine (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SPINTE-GLUTEUS-MACHINE-BG.png' },
    { name: 'Spinte Manubri Panca Piana (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-MANUBRI-PANCA-PIANA-BG.png' },
    { name: 'Spinte Manubri Stabilityall (FITBALL)', path: 'images/exercises/FITBALL/PETTORALI-SPINTE-MANUBRI-STABILITY-BALL-BG.png' },
    { name: 'Spinte Manubri Stabilityall (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-MANUBRI-STABILITY-BALL-BG.png' },
    { name: 'Spinte Paccaassailanciere (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-PACCA-BASSA-BILANCIERE-BG.png' },
    { name: 'Spinte Panca Alta Manubri (PETTORALI)', path: 'images/exercises/PETTORALI/PETTOALI-SPINTE-PANCA-ALTA-MANUBRI-BG.png' },
    { name: 'Spinte Panca Altailanciere (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-PANCA-ALTA-BILANCIERE-BG.png' },
    { name: 'Spinte Panca Pianailanciere 2 (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-PANCA-PIANA-BILANCIERE-2-BG.png' },
    { name: 'Spinte Pancaassa Manubri (PETTORALI)', path: 'images/exercises/PETTORALI/PETTORALI-SPINTE-PANCA-BASSA-MANUBRI-BG.png' },
    { name: 'Spinte Seduto Manubri (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-SPINTE-SEDUTO-MANUBRI-BG.png' },
    { name: 'Spinteilanciere Panca Presa Stretta (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-SPINTE-BILANCIERE-PANCA-PRESA-STRETTA-BG.png' },
    { name: 'Squat 2 Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/QUADRICIPITI-SQUAT-2-KETTLEBELL-V2-BG.png' },
    { name: 'Squat 2 Kettlebell V2 (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-2-KETTLEBELL-V2-BG.png' },
    { name: 'Squat 2manubri (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-2MANUBRI-BG.png' },
    { name: 'Squat Cable Machine (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-CABLE-MACHINE-BG.png' },
    { name: 'Squat Corpo Libero (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-CORPO-LIBERO-BG.png' },
    { name: 'Squat Isometria (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-ISOMETRIA-BG.png' },
    { name: 'Squat Isometria Parete (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-ISOMETRIA-PARETE-BG.png' },
    { name: 'Squat Jump Mani Fianchi (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-JUMP-MANI-FIANCHI-BG.png' },
    { name: 'Squat Jump Prisoner (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-JUMP-PRISONER-BG.png' },
    { name: 'Squat Jumpilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-JUMP-BILANCIERE-BG.png' },
    { name: 'Squat Jumpilanciere Cm (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-JUMP-BILANCIERE-CM-BG.png' },
    { name: 'Squat Multipower (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/quadricipiti-squat-multipower-BG.png' },
    { name: 'Squat Sumo Corpo Libero (GLUTEI)', path: 'images/exercises/GLUTEI/QUADRICIPITI-SQUAT-SUMO-CORPO-LIBERO-BG.png' },
    { name: 'Squat Trx (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-TRX-BG.png' },
    { name: 'Squat Trx (TRX)', path: 'images/exercises/TRX/QUADRICIPITI-SQUAT-TRX-BG.png' },
    { name: 'Squatalzi Sul Posto Mani Fianchi (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-SQUAT-BALZI-SUL-POSTO-MANI-FIANCHI-B.png' },
    { name: 'Squatalzi Sul Posto Prisoner (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-SQUAT-BALZI-SUL-POSTO-PRISONER-B.png' },
    { name: 'Squatalzi Sul Postoilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BALZI-SUL-POSTO-BILANCIERE-BG.png' },
    { name: 'Squatilanciere Parallelo (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BILANCIERE-PARALLELO-BG.png' },
    { name: 'Squatilanciere Profondo (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BILANCIERE-PROFONDO-BG.png' },
    { name: 'Squatox Cable Machine (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BOX-CABLE-MACHINE-BG.png' },
    { name: 'Squatulgaro 2ket (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BULGARO-2KET-BG.png' },
    { name: 'Squatulgaro Trx (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SQUAT-BULGARO-TRX-BG.png' },
    { name: 'Squatulgaro Trx (TRX)', path: 'images/exercises/TRX/QUADRICIPITI-SQUAT-BULGARO-TRX-BG.png' },
    { name: 'Stacchi 1 Kettlebell (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-STACCHI-1-KETTLEBELL-BG.png' },
    { name: 'Stacchi 1 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/DORSALI-STACCHI-1-KETTLEBELL-BG.png' },
    { name: 'Stacchi 2 Kettlebell (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-STACCHI-2-KETTLEBELL-BG.png' },
    { name: 'Stacchi 2 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/DORSALI-STACCHI-2-KETTLEBELL-BG.png' },
    { name: 'Stacchi Cable Machine (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-STACCHI-CABLE-MACHINE-BG.png' },
    { name: 'Stacchi Da Terrailancier V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-STACCHI-DA-TERRA-BILANCIER-V2-BG.png' },
    { name: 'Stacchi Gambe Tese (FEMORALI)', path: 'images/exercises/FEMORALI/FEMORALI-STACCHI-GAMBE-TESE-BG.png' },
    { name: 'Stacco Singola Gamba 2 Kettlebell (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-STACCO-SINGOLA-GAMBA-2-KETTLEBELL-BG.png' },
    { name: 'Stacco Singola Gamba 2 Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/DORSALI-STACCO-SINGOLA-GAMBA-2-KETTLEBELL-BG.png' },
    { name: 'Stacco Sumo Wallball (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-STACCO SUMO- WALLBALL-BG.png' },
    { name: 'Stacco Sumo Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/GLUTEI-STACCO SUMO- WALLBALL-BG.png' },
    { name: 'Stacco Swing 1 Mano Kettlebell (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-STACCO-SWING-1-MANO-KETTLEBELL-BG.png' },
    { name: 'Stacco Swing 1 Mano Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-STACCO-SWING-1-MANO-KETTLEBELL-BG.png' },
    { name: 'Stacco Swing 2 Mani Kettlebell (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-STACCO-SWING-2-MANI-KETTLEBELL-BG.png' },
    { name: 'Stacco Swing 2 Mani Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-STACCO-SWING-2-MANI-KETTLEBELL-BG.png' },
    { name: 'Step (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-STEP.jpg' },
    { name: 'Step Up Cable Machine (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-STEP-UP-CABLE-MACHINE-BG.png' },
    { name: 'Step Up Manubri (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-STEP-UP-MANUBRI-BG.png' },
    { name: 'Step Upilanciere (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-STEP-UP-BILANCIERE-BG.png' },
    { name: 'Stepper (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-STEPPER-B.png' },
    { name: 'Straimaster (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-STRAIMASTER-B.png' },
    { name: 'Sumo Squat 1 Kettlebell V2 (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUMO-SQUAT-1-KETTLEBELL-V2-BG.png' },
    { name: 'Sumo Squat 1 Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SUMO-SQUAT-1-KETTLEBELL-V2-BG.png' },
    { name: 'Sumo Squat Kettlebell V2 (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUMO-SQUAT-KETTLEBELL-V2-BG.png' },
    { name: 'Sumo Squat Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SUMO-SQUAT-KETTLEBELL-V2-BG.png' },
    { name: 'Sumo Squat Manubrio (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUMO-SQUAT-MANUBRIO-BG.png' },
    { name: 'Sumo Squat Trx (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUMO-SQUAT-TRX-BG.png' },
    { name: 'Sumo Squat Trx (TRX)', path: 'images/exercises/TRX/GLUTEI-SUMO-SQUAT-TRX-BG.png' },
    { name: 'Sumo Squatilanciere (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUMO-SQUAT-BILANCIERE-BG.png' },
    { name: 'Superman A Terra (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUPERMAN-A-TERRA-BG.png' },
    { name: 'Superman Su Fitball (FITBALL)', path: 'images/exercises/FITBALL/GLUTEI-SUPERMAN-SU-FITBALL-BG.png' },
    { name: 'Superman Su Fitball (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SUPERMAN-SU-FITBALL-BG.png' },
    { name: 'Suqatulgaro Goblet Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/QUADRICIPITI-SUQAT-BULGARO-GOBLET-KETTLEBELL-V2-BG.png' },
    { name: 'Suqatulgaro Goblet Kettlebell V2 (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPITI-SUQAT-BULGARO-GOBLET-KETTLEBELL-V2-BG.png' },
    { name: 'Suqt Fital Parete (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/QUADRICIPTI-SUQT-FIT-BAL-PARETE-BG.png' },
    { name: 'Swing Due Mani Kettlebell (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SWING-DUE-MANI-KETTLEBELL-BG.png' },
    { name: 'Swing Due Mani Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SWING-DUE-MANI-KETTLEBELL-BG.png' },
    { name: 'Swing One Arm Kettlebell V2 (GLUTEI)', path: 'images/exercises/GLUTEI/GLUTEI-SWING-ONE-ARM-KETTLEBELL-V2-BG.png' },
    { name: 'Swing One Arm Kettlebell V2 (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/GLUTEI-SWING-ONE-ARM-KETTLEBELL-V2-BG.png' },
    { name: 'Tirate Mento Cavi (TRAPEZI)', path: 'images/exercises/TRAPEZI/TRAPEZI-TIRATE-MENTO-CAVI-BG.png' },
    { name: 'Tirate Mentoilanciere (TRAPEZI)', path: 'images/exercises/TRAPEZI/TRAPEZI-TIRATE-MENTO-BILANCIERE-BG.png' },
    { name: 'Tocco Caviglie Altrnato Supino (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TOCCO-CAVIGLIE-ALTRNATO-SUPINO-BG.png' },
    { name: 'Torsioni Al Muro Con Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINAI-TORSIONI-AL-MURO-CON-WALLBALL-BG.png' },
    { name: 'Torsioni Al Muro Con Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINAI-TORSIONI-AL-MURO-CON-WALLBALL-BG.png' },
    { name: 'Torsioni Alte Cable Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI-ALTE-CABLE-MACHINE-BG.png' },
    { name: 'Torsioni Con Lancio Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI-CON-LANCIO-WALLBALL-BG.png' },
    { name: 'Torsioni Con Lancio Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-TORSIONI-CON-LANCIO-WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali A Muro Con Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI-DIAGONALI-A-MURO-CON-WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali A Muro Con Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-TORSIONI-DIAGONALI-A-MURO-CON-WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali In Affondo Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI DIAGONALI-IN AFFONDO- WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali In Affondo Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-TORSIONI DIAGONALI-IN AFFONDO- WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali Seduto Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI- DIAGONALI- SEDUTO- WALLBALL-BG.png' },
    { name: 'Torsioni Diagonali Seduto Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-TORSIONI- DIAGONALI- SEDUTO- WALLBALL-BG.png' },
    { name: 'Torsioni Ginocchio Cable Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOINALI-TORSIONI-GINOCCHIO-CABLE-MACHINE-BG.png' },
    { name: 'Torsioni In Piedi Cable Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOINALI-TORSIONI-IN-PIEDI-CABLE-MACHINE-BG.png' },
    { name: 'Torsioni Seduto Con Wallball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-TORSIONI-SEDUTO-CON-WALLBALL-BG.png' },
    { name: 'Torsioni Seduto Con Wallball (WALLBALL)', path: 'images/exercises/WALLBALL/ADDOMINALI-TORSIONI-SEDUTO-CON-WALLBALL-BG.png' },
    { name: 'Torsioniacino Gambe Piegate (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-torsioni-bacino-gambe-piegate-BG.png' },
    { name: 'Torsioniacino Gambe Tese (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-torsioni-bacino-gambe-tese-BG.png' },
    { name: 'Trazioni Orizzontali Multipower (DORSALI)', path: 'images/exercises/DORSALI/dorsali-trazioni-orizzontali-multipower-BG.png' },
    { name: 'Trazioni Presa Inversa V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-TRAZIONI-PRESA-INVERSA-V2-BG.png' },
    { name: 'Trazioni Pulley Alte (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-TRAZIONI-PULLEY-ALTE-BG.png' },
    { name: 'Trazioni Pulleyasso V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-TRAZIONI-PULLEY-BASSO-V2-BG.png' },
    { name: 'Trazioni Sbarra Avanti V2 (DORSALI)', path: 'images/exercises/DORSALI/DORSALI-TRAZIONI-SBARRA-AVANTI-V2-BG.png' },
    { name: 'Trazioni Tbarilanciere (DORSALI)', path: 'images/exercises/DORSALI/dorsali-Trazioni-Tbar_Bilanciere-BG.png' },
    { name: 'Triceps Press (TRICIPITI)', path: 'images/exercises/TRICIPITI/TRICIPITI-TRICEPS-PRESS-BG.png' },
    { name: 'Tuck Push Up (CARDIO)', path: 'images/exercises/CARDIO/CARDIO-TUCK-PUSH-UP-B.png' },
    { name: 'Upperack Cable Machine (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-UPPER-BACK-CABLE-MACHINE-BG.png' },
    { name: 'Upperack V2 (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-UPPER-BACK-V2-BG.png' },
    { name: 'Upperback Trx (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-UPPERBACK-TRX-BG.png' },
    { name: 'Upperback Trx (TRX)', path: 'images/exercises/TRX/SPALLE-UPPERBACK-TRX-BG.png' },
    { name: 'V.m.o. Leg Extension (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/V.M.O. LEG EXTENSION.png' },
    { name: 'Volare Inverso Manubri Panca Alta (SPALLE)', path: 'images/exercises/SPALLE/SPALLE-VOLARE-INVERSO-MANUBRI-PANCA-ALTA-BG.png' },
    { name: 'Windmill Kettlebell (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ADDOMINALI-WINDMILL-KETTLEBELL-BG.png' },
    { name: 'Windmill Kettlebell (KETTLEBELL)', path: 'images/exercises/KETTLEBELL/ADDOMINALI-WINDMILL-KETTLEBELL-BG.png' },
    { name: 'Abduttori Aperture Abductor Machine Bg (ABDUTTORI)', path: 'images/exercises/ABDUTTORI/ABDUTTORI-APERTURE-ABDUCTOR-MACHINE-BG.png' },
    { name: 'Ab Crunch On A Ball (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ab_crunch_on_a_ball.jpg' },
    { name: 'Ab Machine (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/ab_machine.jpg' },
    { name: 'Abdominal Reverse Curl (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/abdominal_reverse_curl.jpg' },
    { name: 'Abdominal Twist (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/abdominal_twist.jpg' },
    { name: 'Barbell Cable Rollout (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/barbell_cable_rollout.jpg' },
    { name: 'Barbell Rollout (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/barbell_rollout.jpg' },
    { name: 'Bench Leg Raise (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bench_leg_raise.jpg' },
    { name: 'Bench Side Bridge (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bench_side_bridge.jpg' },
    { name: 'Bicycle Kick (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bicycle_kick.jpg' },
    { name: 'Bosu Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bosu_crunch.jpg' },
    { name: 'Bosu Russian Twist (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bosu_russian_twist.jpg' },
    { name: 'Bosu Side Bridge (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bosu_side_bridge.jpg' },
    { name: 'Bosu Sit Up (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/bosu_sit-up.jpg' },
    { name: 'Cable Kneeling Twisting Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/cable_kneeling_twisting_crunch.jpg' },
    { name: 'Cable Standing Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/cable_standing_crunch.jpg' },
    { name: 'Cable Woodchopper (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/cable_woodchopper.jpg' },
    { name: 'Corkscrew (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/corkscrew.jpg' },
    { name: 'Crunch Twist (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/crunch_twist.jpg' },
    { name: 'Cycle Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/cycle_crunch.jpg' },
    { name: 'Decline Twisting Ab Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/decline_twisting_ab_crunch.jpg' },
    { name: 'Dragon Flag (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/dragon_flag.jpg' },
    { name: 'Dumbbell Toe Touch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/dumbbell_toe_touch.jpg' },
    { name: 'Elevated Feet Plank (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/elevated_feet_plank.jpg' },
    { name: 'Hanging Knee Raise (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/hanging_knee_raise.jpg' },
    { name: 'Hanging Leg Raise (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/hanging_leg_raise.jpg' },
    { name: 'High Woodchopper (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/high_woodchopper.jpg' },
    { name: 'Inclined Plank (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/inclined_plank.jpg' },
    { name: 'Inclined Reverse Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/inclined_reverse_crunch.jpg' },
    { name: 'Jackknife (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/jackknife.jpg' },
    { name: 'Kettlebell Crunch (ADDOMINALI)', path: 'images/exercises/ADDOMINALI/kettlebell_crunch.jpg' },
    { name: 'Angled Prone Curl (BICIPITI)', path: 'images/exercises/BICIPITI/angled_prone_curl.jpg' },
    { name: 'Angled Prone Reverse Curl (BICIPITI)', path: 'images/exercises/BICIPITI/angled_prone_reverse_curl.jpg' },
    { name: 'Cable Biceps Curl (BICIPITI)', path: 'images/exercises/BICIPITI/cable_biceps_curl.jpg' },
    { name: 'Concentration Dumbbell Curl (BICIPITI)', path: 'images/exercises/BICIPITI/concentration_dumbbell_curl.jpg' },
    { name: 'Drag Curl (BICIPITI)', path: 'images/exercises/BICIPITI/drag_curl.jpg' },
    { name: 'Dumbbell Biceps Curl (BICIPITI)', path: 'images/exercises/BICIPITI/dumbbell_biceps_curl.jpg' },
    { name: 'Dumbbell Reverse Arm Curl (BICIPITI)', path: 'images/exercises/BICIPITI/dumbbell_reverse_arm_curl.jpg' },
    { name: 'Incline Dumbbell Curl (BICIPITI)', path: 'images/exercises/BICIPITI/incline_dumbbell_curl.jpg' },
    { name: 'Incline Hammer Curl (BICIPITI)', path: 'images/exercises/BICIPITI/incline_hammer_curl.jpg' },
    { name: 'Incline Reverse Curl (BICIPITI)', path: 'images/exercises/BICIPITI/incline_reverse_curl.jpg' },
    { name: 'Burpees (CARDIO)', path: 'images/exercises/CARDIO/burpees.jpg' },
    { name: 'Cycling (CARDIO)', path: 'images/exercises/CARDIO/cycling.jpg' },
    { name: 'Elliptical (CARDIO)', path: 'images/exercises/CARDIO/elliptical.jpg' },
    { name: 'Jump Rope (CARDIO)', path: 'images/exercises/CARDIO/jump_rope.jpg' },
    { name: 'Step Machine (CARDIO)', path: 'images/exercises/CARDIO/step_machine.jpg' },
    { name: 'Back Raise (DORSALI)', path: 'images/exercises/DORSALI/back_raise.jpg' },
    { name: 'Barbell Bent Over Row (DORSALI)', path: 'images/exercises/DORSALI/barbell_bent_over_row.jpg' },
    { name: 'Cable Close Grip Pulldown (DORSALI)', path: 'images/exercises/DORSALI/cable_close_grip_pulldown.jpg' },
    { name: 'Cable Straight Arm Pull Down (DORSALI)', path: 'images/exercises/DORSALI/cable_straight_arm_pull_down.jpg' },
    { name: 'Dumbbell Bench Twist (DORSALI)', path: 'images/exercises/DORSALI/dumbbell_bench_twist.jpg' },
    { name: 'Inverted Row (DORSALI)', path: 'images/exercises/DORSALI/inverted_row.jpg' },
    { name: 'Cable Hamstring Curl (FEMORALI)', path: 'images/exercises/FEMORALI/cable_hamstring_curl.jpg' },
    { name: 'Decline Leg Curl (FEMORALI)', path: 'images/exercises/FEMORALI/decline_leg_curl.jpg' },
    { name: 'Glute Kickback (GLUTEI)', path: 'images/exercises/GLUTEI/glute_kickback.jpg' },
    { name: 'Bosu Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/bosu_pushup.jpg' },
    { name: 'Cable Bent Over Crossover (PETTORALI)', path: 'images/exercises/PETTORALI/cable_bent-over_crossover.jpg' },
    { name: 'Cable Chest Flye (PETTORALI)', path: 'images/exercises/PETTORALI/cable_chest_flye.jpg' },
    { name: 'Cable Chest Press (PETTORALI)', path: 'images/exercises/PETTORALI/cable_chest_press.jpg' },
    { name: 'Cable Crossover (PETTORALI)', path: 'images/exercises/PETTORALI/cable_crossover.jpg' },
    { name: 'Decline Barbell Bench Press (PETTORALI)', path: 'images/exercises/PETTORALI/decline_barbell_bench_press.jpg' },
    { name: 'Decline Close Grip Bench Press (PETTORALI)', path: 'images/exercises/PETTORALI/decline_close_grip_bench_press.jpg' },
    { name: 'Decline Dumbbell Bench Press (PETTORALI)', path: 'images/exercises/PETTORALI/decline_dumbbell_bench_press.jpg' },
    { name: 'Decline Dumbbell Fly (PETTORALI)', path: 'images/exercises/PETTORALI/decline_dumbbell_fly.jpg' },
    { name: 'Decline Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/decline_pushup.jpg' },
    { name: 'Diamond Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/diamond_pushup.jpg' },
    { name: 'Dive Bomber Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/dive-bomber_pushup.jpg' },
    { name: 'Dumbbell Bench Press (PETTORALI)', path: 'images/exercises/PETTORALI/dumbbell_bench_press.jpg' },
    { name: 'Dumbbell Flye (PETTORALI)', path: 'images/exercises/PETTORALI/dumbbell_flye.jpg' },
    { name: 'Dumbbell Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/dumbbell_pushup.jpg' },
    { name: 'Incline Barbell Bench Press (PETTORALI)', path: 'images/exercises/PETTORALI/incline_barbell_bench_press.jpg' },
    { name: 'Incline Dumbbell Fly (PETTORALI)', path: 'images/exercises/PETTORALI/incline_dumbbell_fly.jpg' },
    { name: 'Incline Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/incline_pushup.jpg' },
    { name: 'Kettlebell Pushup (PETTORALI)', path: 'images/exercises/PETTORALI/kettlebell_pushup.jpg' },
    { name: 'Alternating Seated Calf Raise (POLPACCI)', path: 'images/exercises/POLPACCI/alternating_seated_calf_raise.jpg' },
    { name: 'Barbell Standing Calf Raise (POLPACCI)', path: 'images/exercises/POLPACCI/barbell_standing_calf_raise.jpg' },
    { name: 'Calf Raise (POLPACCI)', path: 'images/exercises/POLPACCI/calf_raise.jpg' },
    { name: 'Assisted Dumbbell Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/assisted_dumbbell_lunge.jpg' },
    { name: 'Back Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/back_squat.jpg' },
    { name: 'Barbell Crossover Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_crossover_lunge.jpg' },
    { name: 'Barbell Hack Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_hack_squat.jpg' },
    { name: 'Barbell Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_lunge.jpg' },
    { name: 'Barbell Overhead Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_overhead_squat.jpg' },
    { name: 'Barbell Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_squat.jpg' },
    { name: 'Barbell Sumo Deadlift (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/barbell_sumo_deadlift.jpg' },
    { name: 'Beginner Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/beginner_squat.jpg' },
    { name: 'Bosu Crossover Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/bosu_crossover_lunge.jpg' },
    { name: 'Bosu Jump Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/bosu_jump_squat.jpg' },
    { name: 'Bosu Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/bosu_lunge.jpg' },
    { name: 'Box Jump (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/box_jump.jpg' },
    { name: 'Bulgarian Split Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/bulgarian_split_squat.jpg' },
    { name: 'Bulgarian Split Squat No Weight (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/bulgarian_split_squat_no_weight.jpg' },
    { name: 'Dead Lift (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/dead_lift.jpg' },
    { name: 'Dumbbell Barbell Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/dumbbell_barbell_lunge.jpg' },
    { name: 'Dumbbell Deadlift (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/dumbbell_deadlift.jpg' },
    { name: 'Dumbbell Lunge (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/dumbbell_lunge.jpg' },
    { name: 'Front Squat (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/front_squat.jpg' },
    { name: 'Kettlebell Clean (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/kettlebell_clean.jpg' },
    { name: 'Lunging Step Up (QUADRICIPITI)', path: 'images/exercises/QUADRICIPITI/lunging_step_up.jpg' },
    { name: 'Arnold Press (SPALLE)', path: 'images/exercises/SPALLE/arnold_press.jpg' },
    { name: 'Barbell Behind Neck Press (SPALLE)', path: 'images/exercises/SPALLE/barbell_behind_neck_press.jpg' },
    { name: 'Barbell Split Jerk (SPALLE)', path: 'images/exercises/SPALLE/barbell_split_jerk.jpg' },
    { name: 'Cable Diagonal Raise (SPALLE)', path: 'images/exercises/SPALLE/cable_diagonal_raise.jpg' },
    { name: 'Cable Face Pull (SPALLE)', path: 'images/exercises/SPALLE/cable_face_pull.jpg' },
    { name: 'Cable Front Raise (SPALLE)', path: 'images/exercises/SPALLE/cable_front_raise.jpg' },
    { name: 'Cable Military Press (SPALLE)', path: 'images/exercises/SPALLE/cable_military_press.jpg' },
    { name: 'Cable Rear Lateral Raise (SPALLE)', path: 'images/exercises/SPALLE/cable_rear_lateral_raise.jpg' },
    { name: 'Cable Side Lateral Raise (SPALLE)', path: 'images/exercises/SPALLE/cable_side_lateral_raise.jpg' },
    { name: 'Front Plate Raise (SPALLE)', path: 'images/exercises/SPALLE/front_plate_raise.jpg' },
    { name: 'High Pull (SPALLE)', path: 'images/exercises/SPALLE/high_pull.jpg' },
    { name: 'Incline Shoulder Rotation (SPALLE)', path: 'images/exercises/SPALLE/incline_shoulder_rotation.jpg' },
    { name: 'Incline Y Raise (SPALLE)', path: 'images/exercises/SPALLE/incline_y_raise.jpg' },
    { name: 'Bar Upright Row (TRAPEZI)', path: 'images/exercises/TRAPEZI/bar_upright_row.jpg' },
    { name: 'Barbell Shrug (TRAPEZI)', path: 'images/exercises/TRAPEZI/barbell_shrug.jpg' },
    { name: 'Kettlebell High Pull (TRAPEZI)', path: 'images/exercises/TRAPEZI/kettlebell_high_pull.jpg' },
    { name: 'Bench Dip (TRICIPITI)', path: 'images/exercises/TRICIPITI/bench_dip.jpg' },
    { name: 'Cable Triceps Overhead Extension (TRICIPITI)', path: 'images/exercises/TRICIPITI/cable_triceps_overhead_extension.jpg' },
    { name: 'Cable Triceps Pushdown (TRICIPITI)', path: 'images/exercises/TRICIPITI/cable_triceps_pushdown.jpg' },
    { name: 'Dip (TRICIPITI)', path: 'images/exercises/TRICIPITI/dip.jpg' },
    { name: 'Dumbbell Pull Over (TRICIPITI)', path: 'images/exercises/TRICIPITI/dumbbell_pull_over.jpg' },
    { name: 'French Press (TRICIPITI)', path: 'images/exercises/TRICIPITI/french_press.jpg' }
];
